# Generated by Django 4.1.7 on 2023-10-14 17:12

from django.db import migrations
import useraccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_color',
            field=useraccount.models.RGBcolorField(max_length=6, null=True),
        ),
    ]
